name: eccsplorer_slim
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.9
  - numpy
  - scipy
  - biopython
  - r-base>=4.0
  - r-ggplot2
  - r-ggrepel
  - r-gridextra
  - r-dplyr
